依存パッケージのバージョンを上げる
cloudnativedaysjp/dreamkast-ui pull request #217
Opened 2022-04-30 06:55 UTC by maktak1995

リベンジ

2022-04-30 10:46 UTC, maktak1995 commented
jestの最新はv28だけど、ts-jestがまだ対応できていないのでv27
reactはv18にするとレンダリングの仕様変更で即死したので一旦v17で

2022-05-01 08:24 UTC, jacopen requested changes
@maktak1995 
内容はよさそうです！
もうひとつのPRマージしたらコンフリクトが起きてしまったので、そこだけ解消していただければー！

2022-05-01 09:55 UTC, showks-containerdaysjp commented
Review app

https://dreamkast-ui-217.dev.cloudnativedays.jp

2022-05-17 04:47 UTC, maktak1995 commented
@jacopen 
コンフリクト解消できたので確認お願いします〜
自分の手元ではnginxの設定ができてなくてローカルで確認できてないですが、動作に影響するレベルの書き換えはしていないはずなので他のみなさんが現状問題ないなら大丈夫だと思います

2022-05-17 05:10 UTC, jacopen approved these changes

2022-05-17 05:11 UTC, merged