セッション自動切り替え時のカウントダウン実装
cloudnativedaysjp/dreamkast-ui pull request #229
Opened 2022-07-26 16:26 UTC by maktak1995

#226

<img width="897" alt="スクリーンショット 2022-07-27 1 25 35" src="https://user-images.githubusercontent.com/11240481/181059935-1c7ef129-e73e-467d-a8ed-e997d938f630.png">

2022-07-26 16:27 UTC, dreamkast-cloudnativedays commented
Review app

https://dreamkast-ui-229.dev.cloudnativedays.jp

2022-07-28 15:28 UTC, jacopen requested changes
Reviewapps
https://dreamkast-ui-229.dev.cloudnativedays.jp/cnsec2022

で動作確認をしていたんですけど、管理画面でセッションを切り替えるとカウントダウンは正しく表示されるものの、切り替わらずにカウントダウンがまた5秒から再度始まるループになることがあります。

セッションを色々切り替えていると問題無く切り替わることもあります

このReviewAppで再現するんじゃないかなって思うのでちょっと見てもらって良いですか？

2022-07-29 15:37 UTC, jacopen commented
WebSocketで切り替えイベントを受け取ると、カウントダウンは表示される&そこの表示されるセッションは次セッションのタイトルになっていて、これは問題無い感じです。(上記ループ問題は起きますが)

ただ、
- TalkInfoの中身が空っぽになってしまう
  - 1回目のカウントダウンループ終了後に次セッションのInfoが出る

という状態になってしまうようです。
希望する状態としては

- カウントダウンが完了するまではTalkInfoは前のセッションのまま
- カウントダウン終了後に動画が切り替わると共に次セッションのTalkInfoが表示される

という感じです

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/79102/181794054-3f91a476-5b6a-42f8-9d8b-9084822bddbb.png">

2022-07-31 05:58 UTC, jacopen approved these changes
めっちゃ良い感じなりました！！！！！！

実装ありがとうございますーーー

2022-07-31 05:59 UTC, merged