Refine chat
cloudnativedaysjp/dreamkast-ui pull request #47
Opened 2021-02-21 09:38 UTC by takaishi

- チャットメッセージに情報を追加
  - 投稿者のProfileIDとSpeakerID
  - チャットかQAかを見分けるフラグ
  - 表示切り替えのタブを追加（チャットとQA両方表示、QAだけ表示）
- 質問を送るためのチェックボックスを追加
- アクション用ボタンを設置
- その他見た目など修正

2021-02-21 10:10 UTC, jacopen requested changes
はやめにStyledComponentに切り替えておいた方が楽かなと

2021-02-21 11:28 UTC, jacopen requested changes

2021-02-21 11:28 UTC, jacopen commented on src/components/Chat/Chat.tsx
> +  function a11yProps(index: any) {
anyじゃないとだめ？

2021-02-21 11:28 UTC, jacopen commented on src/components/Chat/ChatMessage.tsx
> +    if (chatMessage.speaker_id) {
この条件文って意図した通り？ speaker_idが入ってればそれでspeakerとみなせるのかな

2021-02-21 11:28 UTC, jacopen commented on src/components/Chat/ChatMessage.tsx
> +    if (chatMessage.speaker_id) {
これが意図した通りだとすると、こんな感じで書けばもっとシンプルかも

```
return typeof chatMessage.speaker_id == "number"
```

2021-02-21 12:14 UTC, maktak1995 requested changes
いくつかコメントいたしました！

2021-02-21 12:14 UTC, maktak1995 commented on src/components/Chat/ChatMessage.tsx
> +    if (chatMessage.speaker_id) {
ここは↓の記法のほうがスッキリしていいと思います〜
```js
const isSpeakerMessage = !!chatMessage.speaker_id;
```

2021-02-21 12:14 UTC, maktak1995 commented on src/components/Chat/ChatMessageForm.tsx
> +      </Button>
絵文字送れるのすごくいいですね！

2021-02-21 12:14 UTC, maktak1995 commented on src/components/Chat/styled.ts
> +  background: #ffffff;
propsを受け取ってスタイルを変えるときは以下の表現のほうがメジャーですね
すっきりしているのでこの書き方のほうがおすすめです
```js
background: ${ ({ isChat }) => isChat ? '#f5f5f5' : '#ffffff' };
```

2021-02-21 15:56 UTC, takaishi commented on src/components/Chat/ChatMessage.tsx
> +    if (chatMessage.speaker_id) {
意図通り。

2021-02-22 04:40 UTC, jacopen reviewed
自分としてはOK!

2021-02-22 09:01 UTC, maktak1995 approved these changes
LGTM！

2021-02-22 11:46 UTC, jacopen approved these changes

2021-02-22 11:46 UTC, merged