イベント受付用のページでプリンターを選択可能にする
cloudnativedaysjp/dreamkast-ui pull request #521
Opened 2024-11-17 07:11 UTC by takaishi

2024-11-20 11:01 UTC, jacopen-pd requested changes

2024-11-20 11:01 UTC, jacopen-pd commented on .github/workflows/build-branch.yml
> +    branches:
中身が消えちゃってる

2024-11-20 11:01 UTC, jacopen-pd commented on .github/workflows/build-branch.yml
> +    branches:
```suggestion
    branches: ["*"]
```

2024-11-20 11:07 UTC, takaishi commented on .github/workflows/build-branch.yml
> +    branches:
`["*"]` をつけてるとブランチプッシュでワークフローがなぜか走らないんよ。

2024-11-21 10:21 UTC, jacopen approved these changes

2024-11-21 10:21 UTC, merged