認証まわりの(仮)対応
cloudnativedaysjp/dreamkast-ui pull request #54
Opened 2021-02-23 15:30 UTC by maktak1995

* ログアウトボタンをheaderに設置
* Chat APIがコケたら (ログインしていなかったら) トップページに遷移

2021-02-23 15:55 UTC, jacopen requested changes

2021-02-23 15:55 UTC, jacopen commented on src/components/Chat/Chat.tsx
> +          window.location.href = `${window.location.href.replace(/ui/g, '')}`
Review appsで偶然誤爆が起きて気づいたのだけど、
```
https://dreamkast-ui-54.dev.cloudnativedays.jp/cndo2021/ui/
```
だと
```
https://dreamkast--54.dev.cloudnativedays.jp/cndo2021//
```

にリダイレクトされるという状態になりました。

```suggestion
          window.location.href = `${window.location.href.replace(/\/ui\//g, '')}`
```

とかどうでしょ

2021-02-24 01:30 UTC, maktak1995 commented on src/components/Chat/Chat.tsx
> +          window.location.href = `${window.location.href.replace(/ui/g, '')}`
そのほうがよさそうですね！取り入れます

2021-02-24 10:18 UTC, jacopen approved these changes

2021-02-24 10:18 UTC, merged