ブース一覧とブースページを追加
cloudnativedaysjp/dreamkast-ui pull request #85
Opened 2021-03-01 09:33 UTC by takaishi

https://github.com/cloudnativedaysjp/dreamkast-ui/issues/20

2021-03-01 09:39 UTC, takaishi commented
あれ？プレビューアプリが作られない？

2021-03-01 14:41 UTC, jacopen commented
ありゃ、調べる

2021-03-01 14:42 UTC, jacopen commented
何故かActionsがスタックしてる
![image](https://user-images.githubusercontent.com/79102/109512724-bb19db00-7ae7-11eb-8ebf-0daccccd6516.png)

2021-03-01 14:46 UTC, jacopen commented
もしかするとコンフリクトしているせいかもしれないので、コンフリクト解消してもらっていいですか @takaishi

2021-03-01 17:18 UTC, ShotaKitazawa commented
この時間の GitHub Actions が調子が悪かったのを Twitter でも観測しているので、再度 push するなどして Actions を re-run してもらうと動くと思います〜

2021-03-03 12:53 UTC, jacopen commented
んー、なんか403になっちゃうなぁ
https://dreamkast-ui-85.dev.cloudnativedays.jp/cndo2021/ui/booths/

2021-03-03 13:51 UTC, jacopen requested changes
Review appsが上手く動いて居ない様子。

手元で動かしてみたけど、これまた想定通りに動いて居るかどうか不明･･･

/cndo2021/ui/booths/  -> 404
![image](https://user-images.githubusercontent.com/79102/109815131-a74eb000-7c72-11eb-98a7-c71a08f7e4da.png)

/cndo2021/ui/booths/10 -> レイアウト崩れ

![image](https://user-images.githubusercontent.com/79102/109815332-e0872000-7c72-11eb-9067-812283fdf9bd.png)

2021-03-03 14:22 UTC, takaishi commented on src/components/Booths/Booths.tsx
> +    <Styled.Container id="foofoo">
これはなんかのゴミだな…

2021-03-03 14:41 UTC, takaishi commented
review appがなんか動きおかしいの、APIが古い気がする。

2021-03-03 15:26 UTC, takaishi commented
review appsのAPIが古い問題は解消されたけど次は無限にリダイレクトしちゃっている…

```
2021/03/03 15:26:13 [error] 30#30: *587 rewrite or internal redirection cycle while internally redirecting to "////////////cndo2021/ui/booths/10.html.html.html.html.html.html.html.html.html.html.html", client: 10.100.210.183, server: localhost, request: "GET /cndo2021/ui/booths/10 HTTP/1.1", host: "dreamkast-ui-85.dev.cloudnativedays.jp", referrer: "https://dreamkast-ui-85.dev.cloudnativedays.jp/cndo2021/ui/"
```

2021-03-03 17:34 UTC, jacopen commented
あー・・・Nginx側の作りを変えないといけないかも

2021-03-04 00:33 UTC, takaishi commented
朝朝起きて見たらnginxのデフォルトページが表示されるようになった…？

![image](https://user-images.githubusercontent.com/107187/109891543-9e8ac800-7ccc-11eb-8dcf-3cede1754a0c.png)

2021-03-04 00:33 UTC, takaishi commented
あ、コミットが積まれていた影響かな。

2021-03-04 00:57 UTC, takaishi commented
うーん、今の構成だとビルド時に静的ページを生成しないといけなさそうな気配。 @maktak1995 の見解も聞きたい

2021-03-04 01:04 UTC, takaishi commented
react-routerを使えば動的なルーティングが可能？

2021-03-04 03:04 UTC, jacopen commented
手元とingress経由で挙動が異なるのもまた悩ましい

2021-03-04 06:44 UTC, jacopen requested changes
![image](https://user-images.githubusercontent.com/79102/109921881-dfe89b00-7cff-11eb-933e-e011fcaba0e8.png)
SSR化で出るようになった。その上で気になった点
- Miroを設定していなくても『オンラインホワイトボード』のヘッダが出てしまう
- Vimeo埋め込みが固定値になっていてサイズ感が合っていない(大きくすると違和感が、小さくするとはみ出る)
- Miro, Vimeoともに空欄にしてもスペースを消費してしまい、PDF欄が下に追いやられる

あたりが気になりました

2021-03-04 08:49 UTC, jacopen commented
@takaishi このあたりの見た目の調整、自分の方で巻き取るねー

2021-03-04 14:08 UTC, takaishi commented
> @takaishi このあたりの見た目の調整、自分の方で巻き取るねー

はーい。あざます

2021-03-05 15:45 UTC, maktak1995 reviewed
コードには問題はありませんが、デザインにいくつか気になる点があったのでコメントいたしました！
早く利用できるようにしたいということであれば、このままリリースしてもOKだと思います！

2021-03-05 15:45 UTC, maktak1995 commented on src/components/BoothPage/BoothPage.tsx
> +  const leftPane = () => {
企業ロゴと企業説明をLeftPaneに分けているのはなぜでしょうか？
RightPaneに比べ要素が少ないので、全体的にアンバランスに感じます。
よくあるLPみたいな要素を縦に並べるレイアウト(+サイドバー？)が合っているように感じるのですが
どうでしょうか？

2021-03-05 15:45 UTC, maktak1995 commented on src/components/BoothPage/BoothPage.tsx
> +            </h2>
ダッシュボードも意識的にやっているのですが、全体にメリハリを出すために見出しの文字色には `#037f8c` を利用しています。( [利用例](https://github.com/cloudnativedaysjp/dreamkast-ui/blob/20581b88fc727191dc8d64761e5213e4b775fbc7/src/components/TalkInfo/styled.ts#L17) )
なので、ブースページの見出しも同様にしてほしいです。

2021-03-06 04:33 UTC, jacopen commented on src/components/BoothPage/BoothPage.tsx
> +            </h2>
ういっす！

2021-03-06 04:34 UTC, jacopen commented on src/components/BoothPage/BoothPage.tsx
> +  const leftPane = () => {
そうねぇ、要素の少なさは思った。

@takaishi とくに左ペインに今後要素追加する想定がなかったら1ペインにしたほうがいいかもだけど、どうー？

2021-03-06 06:29 UTC, takaishi commented on src/components/BoothPage/BoothPage.tsx
> +  const leftPane = () => {
今あるコンテンツだけでも１ペインだと下の方見られにくいんじゃないかなあと思うんだよね。

2021-03-06 06:31 UTC, takaishi commented on src/components/BoothPage/BoothPage.tsx
> +  const leftPane = () => {
左右でコンテンツ数のバランスが悪いというのは同意

2021-03-06 07:57 UTC, maktak1995 approved these changes
LGTM！

2021-03-06 09:59 UTC, merged