チャットは新しいメッセージを下に追加していくスタイルに戻す
cloudnativedaysjp/dreamkast-ui pull request #96
Opened 2021-03-03 14:31 UTC by takaishi

fix https://github.com/cloudnativedaysjp/dreamkast-ui/issues/93

2021-03-03 14:56 UTC, jacopen requested changes
下に追加自体は問題なさそう

ただこの場合スクロールバーに追従する仕組みが必要かな・・
![image](https://user-images.githubusercontent.com/79102/109824280-0664f280-7c7c-11eb-9420-d4887a6f559f.png)

2021-03-03 15:07 UTC, takaishi commented
アー、単純にオートスクロールするだけだとリプライするときに困るのでどうやるのがいいかちょっと調べないといけない

2021-03-03 15:16 UTC, jacopen commented
なるほど・・・ちょっと手間かもだから、優先順位落として一旦別のissueに着手した方がいいかもしれないね。機能的には上スクロールでも困りはしないので

2021-03-04 18:11 UTC, jacopen commented
#104 で盛り込まれたのでこちら閉じちゃいます

2021-03-04 18:11 UTC, closed without merging